export * from './LetraTitulo'
export * from './LetraParrafo'
export * from './Lista'
export * from './BtnPrincipal'
export * from './Formulario'
export * from './Filtrar'
export * from './Paginacion'
export * from './PerdidosTarjeta'
